name: Build
on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-16.04
            platform: linux
          - name: macOS
            os: macos-latest
            platform: mac
          - name: Windows
            os: windows-latest
            platform: windows
        # cfg:
        # - { name: Linux, os: ubuntu-16.04, platform: linux }
        # - { name: macOS, os: macos-latest, platform: mac }
        # - { name: Windows, os: windows-latest, platform: windows }
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        if: ${{ matrix.platform == 'linux' }}
        run: |
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install -y gcc-6 g++-6 freeglut3-dev g++ libasound2-dev libcurl4-openssl-dev libfreetype6-dev libjack-jackd2-dev libx11-dev libxcomposite-dev libxcursor-dev libxinerama-dev libxrandr-dev mesa-common-dev ladspa-sdk webkit2gtk-4.0 libgtk-3-dev xvfb
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Run script"
        run: ./install/build
        shell: bash
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.name }}
          path: ci/${{ matrix.platform }}/bin