name: Build
on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Linux
            os: ubuntu-16.04
            platform: linux
          - name: macOS
            os: macos-latest
            platform: mac
          - name: Windows
            os: windows-latest
            platform: windows
        # cfg:
        # - { name: Linux, os: ubuntu-16.04, platform: linux }
        # - { name: macOS, os: macos-latest, platform: mac }
        # - { name: Windows, os: windows-latest, platform: windows }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: "Run script"
        run: ./install/build
        shell: bash
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.name }}
          path: ci/${{ matrix.platform }}/bin