name: Build
on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-16.04
            platform: linux
          - name: macOS
            os: macos-latest
            platform: mac
          - name: Windows
            os: windows-2016
            platform: windows
        # cfg:
        # - { name: Linux, os: ubuntu-16.04, platform: linux }
        # - { name: macOS, os: macos-latest, platform: mac }
        # - { name: Windows, os: windows-latest, platform: windows }
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        if: ${{ matrix.platform == 'linux' }}
        run: |
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install -y gcc-6 g++-6 freeglut3-dev g++ libasound2-dev libcurl4-openssl-dev libfreetype6-dev libjack-jackd2-dev libx11-dev libxcomposite-dev libxcursor-dev libxinerama-dev libxrandr-dev mesa-common-dev ladspa-sdk webkit2gtk-4.0 libgtk-3-dev xvfb
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Run script"
        run: |
          export MSBUILD_EXE="C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe"
          ./install/install_macos_certificate
          ./install/build
        shell: bash
        env:
          VST2_SDK_URL: ${{ secrets.VST2_SDK_URL }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
          DEV_CERT_APP: ${{ secrets.DEV_CERT_APP }}
          DEV_CERT_INST: ${{ secrets.DEV_CERT_INST }}
          DEV_ID_APP: ${{ secrets.DEV_ID_APP }}
          DEV_ID_INST: ${{ secrets.DEV_ID_INST }}
      - name: Notarize
        if: ${{ matrix.platform == 'mac' }}
        run: ./install/notarise ./bin/mac/pluginval_macOS.zip com.tracktion.pluginval ${AC_USERNAME} ${AC_PASSWORD}
        shell: bash
        env:
          AC_USERNAME: ${{ AC_USERNAME }}
          AC_PASSWORD: ${{ AC_PASSWORD }}
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.name }}
          path: ./bin/${{ matrix.platform }}